import { Document, Page, View, Text } from "@react-pdf/renderer";
import { StyleSheet } from "@react-pdf/renderer";
import type { DocumentConfig, DocumentField } from "@/config/documents";
import type { DocumentFields } from "@/types/document";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    paddingTop: 50,
    paddingBottom: 60,
    paddingHorizontal: 55,
    color: "#1a1a1a",
  },
  title: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    marginBottom: 20,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: "#cccccc",
    marginVertical: 12,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    marginTop: 14,
    marginBottom: 4,
  },
  fieldRow: {
    flexDirection: "row",
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#eeeeee",
    paddingBottom: 6,
  },
  fieldLabel: {
    width: 140,
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#444444",
    paddingRight: 8,
    flexShrink: 0,
  },
  fieldValue: {
    flex: 1,
    fontSize: 10,
    lineHeight: 1.4,
    color: "#1a1a1a",
  },
  emptyValue: {
    flex: 1,
    fontSize: 10,
    color: "#aaaaaa",
    fontStyle: "italic",
  },
  footer: {
    fontSize: 8,
    color: "#777",
    textAlign: "center",
    marginTop: 20,
  },
});

interface Props {
  doc: DocumentConfig;
  fields: DocumentFields;
}

function FieldRow({ field, fields }: { field: DocumentField; fields: DocumentFields }) {
  const value = fields[field.name];
  return (
    <View style={styles.fieldRow}>
      <Text style={styles.fieldLabel}>{field.label}</Text>
      {value ? (
        <Text style={styles.fieldValue}>{value}</Text>
      ) : (
        <Text style={styles.emptyValue}>Not yet provided</Text>
      )}
    </View>
  );
}

export default function GenericDocument({ doc, fields }: Props) {
  return (
    <Document title={doc.name} author="PreLegal" subject={doc.name}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{doc.name}</Text>

        <View style={styles.divider} />

        <Text style={styles.sectionTitle}>Key Terms</Text>

        {doc.fields.map((field) => (
          <FieldRow key={field.name} field={field} fields={fields} />
        ))}

        <Text style={styles.footer}>
          Generated by PreLegal. This document is a draft only and is subject to legal review before use.
        </Text>
      </Page>
    </Document>
  );
}
